name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      # Paso Intermedio: Hacer que app.html actúe como la página principal de cara al público
      - name: Set app.html as the primary landing page
        run: |
          cp ./ui_web/index.html ./ui_web/diagnostico.html
          cp ./ui_web/app.html ./ui_web/index.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './ui_web'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
